name: tcllibraryapp_develop
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.1.35+37

#flutter version : 3.24.5

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  hive_flutter: ^1.1.0
  provider: ^6.1.5
  path_provider: ^2.1.5
  http: ^1.4.0
  intl: ^0.20.2
  url_launcher: ^6.3.2
  # flutter_typeahead: ^4.3.2
  # modal_progress_hud_nsn: ^0.4.0
  flutter_spinkit: ^5.2.1
  # number_to_character: ^0.0.12
  pdf: ^3.11.3
  device_info_plus: ^11.5.0
  permission_handler: ^12.0.1
  open_file: ^3.5.10
  fluttertoast: ^8.2.12
  get: ^4.7.2
  avatar_glow: ^2.0.2
  connectivity_plus: ^6.1.4
  dartz: ^0.10.1
  equatable: ^2.0.7
  local_auth: ^2.3.0
  upgrader:
  google_maps_flutter: ^2.12.3
  #  flutter_google_places: ^0.3.0
  #  google_maps_webservice: ^0.0.19
  #  google_maps_webservice: 0.0.20-nullsafety.5
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.0
  flutter_screenutil: ^5.9.3
  image_picker:
  image_cropper:
  animated_bottom_navigation_bar: ^1.4.0
  flutter_rating_bar: ^4.0.1
  audioplayers: ^6.5.0
  audioplayers_darwin: ^6.3.0
  sliver_tools: ^0.2.12
  flutter_pdfview: ^1.4.1+1
  country_picker: ^2.0.27
  # path
  file_picker: ^8.0.3
  path: ^1.9.0
  syncfusion_flutter_pdfviewer: ^30.1.41
  image: ^4.5.4
  pdf_image_renderer:
  #  page_flip: ^0.1.0
  zoom_widget: ^2.0.1
  loading_animation_widget: ^1.3.0
  video_player: ^2.10.0
  # youtube_player_flutter: ^8.1.2
  chewie: ^1.12.1
  flutter_html: ^3.0.0
  quill_html_editor_v2: ^2.2.10
  shimmer: ^3.0.0
  firebase_messaging: ^15.2.10
  firebase_core: ^3.15.2
  flutter_local_notifications: ^19.4.0
  overlay_support: ^2.1.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.6
  firebase_auth: ^5.7.0
  # flutter_animated_dialog: 
  uuid: ^4.5.1
  purchases_flutter: ^9.1.0
  ip_country_lookup: ^1.0.3
  # flutter_paypal_payment: ^1.0.6
  flutter_easyloading: ^3.0.5
  http_parser:
  # flutter_windowmanager: ^0.2.0
  screen_protector: ^1.4.2+1
  flutter_paypal:
  flutter_inappwebview: ^6.1.5
  flutter_tawkto: ^0.0.5



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/pdfs/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
